---
name: Priyanka 
surname: Gagneja
address: "63 Beaver Dam Rd, Natick, MA-01760"
www: "priyankagagneja.github.io"
email: "priyankaigit@gmail.com"
github: priyankagagneja
linkedin: priyanka-gagneja
twitter: priyankaigit
date: "`r format(Sys.time(), '%B %Y')`"

aboutme: "Passionate, self-motivated Analytics/Consulting professional worked across industries like retail, education & financial services. Curious, Quick learner, relentless and always willing to learn new tools and technologies. Looking forward to exploring a variety of opportunities that data can bring"

docname: "CV"
urlcolor: blue
output: vitae::hyndman
---

```{r setup, include=FALSE}
# headcolor: 990000
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = here("data.r"))
```

# Skills

```{r SKILLS}
skills %>%
  detailed_entries(
    when = area,
    what = skills
  )
```

# Community Engagement

```{r WORKS}
community_eng %>%
  detailed_entries(
    with = glue::glue("{detail} ({where})",.na = ""),
    what =  inst,
    #why = detail,
    when = startYear ,
    # where = where
  )
```

# Employment

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    # with = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    what = glue::glue("{title} @ {unit} - {where}"),
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = "")
    #where = where
  )
``` 

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = glue::glue("{inst}, {where}"),
    what = degree,
    why = detail,
    when = glue::glue("{startYear} - {endYear}",.na = "")
    # where = where
  )
```